name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Ensure Docker is working
      - name: Check Docker Setup
        run: docker --version

      # Docker Login
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and Push Docker Image
      - name: Docker build and push
        run: |
          docker build -t myntra .
          docker tag myntra jinesh1893/myntra:latest
          docker push jinesh1893/myntra:latest
