name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Ensure Docker is working
      - name: Check Docker Setup
        run: docker --version

      # Install Docker Scout
      - name: Install Docker Scout
        run: |
          curl -fsSL https://downloads.docker.com/cli/scout/linux/amd64/docker-scout-linux-amd64.tar.gz -o docker-scout-linux-amd64.tar.gz
          tar xz -C /usr/local/bin -f docker-scout-linux-amd64.tar.gz
        
      # Docker Login
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker Scout Scan
      - name: Docker Scout Scan
        run: |
          docker-scout quickview fs://.
          docker-scout cves fs://.

      # Build and Push Docker Image
      - name: Docker build and push
        run: |
          docker build -t myntra .
          docker tag myntra sevenajay/myntra:latest
          docker push sevenajay/myntra:latest

      # Docker Scout Image Scan
      - name: Docker Scout Image Scan
        run: |
          docker-scout quickview sevenajay/myntra:latest
          docker-scout cves sevenajay/myntra:latest
