name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This version is already compatible with Node.js v20

      - name: Set up Node.js
        uses: actions/setup-node@v3  # This version is already compatible with Node.js v20
        with:
          node-version: '20'

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          args: >
            -Dsonar.projectKey=sqp_6aa16b70acc20b99ab4da7f8d304932548e86ad2
            -Dsonar.projectName="My Project Name"
            -Dsonar.sources=./src
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Uncomment if you want to enforce quality gate checks
      # - name: SonarQube Quality Gate
      #   uses: sonarsource/sonarqube-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
